#!/usr/bin/env bash
# How to install a load balancer

sudo apt-get -y update
apt-get -y install haproxy

server_config=\ 
"
frontend  JoanWaithira_frontend
        bind *:80
        mode http
        default_backend JoanWaithira_backend
backend JoanWaithira_backend
        balance roundrobin
        server 402408-web-01 54.82.179.171:80 check
        server 402408-web-02 100.25.132.241:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
