#!/usr/bin/env bash
#This script displays "Best School" 10 times and hi at the end
i=0
while ((i < 10))
do
	((i++))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
